# Generated by Django 5.1.1 on 2024-09-29 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MalwareAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.evidence')),
            ],
        ),
    ]
